---
title: "cluster-analysis"
author: "Chloe, Marykate, Kaddijatou"
date: "04/09/2024"
output: 
  github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)

# Note: Before knitting, make sure you"ve installed the packages used in the
# sections below

packages <- c("knitr", "tidyverse", "readr","devtools", "psych", "cluster", "factoextra",
              "gridExtra", "grid", "here", "rlang", "sf", "urbnthemes", "mclust",
              "dbscan", "data.table", "R.utils")

## INSTALL PACKAGES
packages <- lapply(packages, FUN = function(x) {
  if (!require(x, character.only = TRUE)) {
    if (x == "urbnthemes") {
      devtools::install_github("UrbanInstitute/urbnthemes")
    } else {
    install.packages(x)
    }
    library(x, character.only = TRUE)}})

set_urbn_defaults(style = "print")

```

Source cluster analysis functions 
```{r}
# Define trial name for modeling run
trial_name <- "seattle_arrests"

source("cluster-functions.R")
source("data_viz_functions.R")
```

# Read and Pre-Process Data

```{r cars}
# Load all Seattle data and reporting boundaries data
SPD_Call_Data <- read_csv("~/Documents/Development/DAT4500/Data/SPD_Call_Data_2023.csv")
SPD_Arrest_Data <- read_csv("~/Documents/Development/DAT4500/Data/SPD_Arrest_Data_2023.csv")
SPD_Crime_Data <- read_csv("~/Documents/Development/DAT4500/Data/SPD_Crime_Data__2023.csv")
SPD_Stops_Data <- read_csv("~/Documents/Development/DAT4500/Data/SPD_Stops_Data_2023.csv")
SPD_Reporting_Boundries <- read_csv("~/Documents/Development/DAT4500/Data/SPD_Reporting_Boundries_2023.csv")
census2020 <- read_csv("~/Documents/Development/DAT4500/Data/census2020.csv")
```


```{r}
## data for census and arrest rates by race 

census2020 <- read_csv("~/Desktop/DAT4500/census2020.csv", 
    col_types = cols(`King County, Washington!!Estimate` = col_skip(), 
        `King County, Washington!!Margin of Error` = col_skip(), 
        `King County, Washington!!Percent` = col_skip(), 
        `King County, Washington!!Percent Margin of Error` = col_skip(), 
        `Seattle city, Washington!!Margin of Error` = col_skip(), 
         `Seattle city, Washington!!Percent Margin of Error` = col_skip()))
 View(census2020)      
 

SPD_Arrest_Data <- SPD_Arrest_Data_2023 %>%
  rename_with(~ gsub(" ", "_", .x), everything()) 

arrest_totals_by_race <- SPD_Arrest_Data %>%
  group_by(Subject_Race) %>%
  summarize(Arrest_Count = n(), .groups = 'drop')

head(arrest_totals_by_race)
```


```{r}
SPD_Arrest_Data <- SPD_Arrest_Data %>%
  rename_with(~ gsub(" ", "_", .x), everything())
```


# Arrest Count Per Race

```{r}
arrest_counts_by_race <- SPD_Arrest_Data %>%
  group_by(Beat, Subject_Race, Precinct) %>%
  summarize(Arrest_Count = n(), .groups = 'drop')

head(arrest_counts_by_race)
```


```{r}
# Total arrests 
arrest_counts_by_race <- SPD_Arrest_Data %>%
  group_by(Beat, Subject_Race, Precinct) %>%
  summarize(Arrest_Count = n(), .groups = 'drop')

total_arrests_by_beat <- arrest_counts_by_race %>%
  group_by(Beat, Precinct) %>%
  summarize(Total_Arrests = sum(Arrest_Count), .groups = 'drop')

arrest_proportions_by_race <- arrest_counts_by_race %>%
  left_join(total_arrests_by_beat, by = c("Beat", "Precinct")) %>%
  mutate(Proportion = Arrest_Count / Total_Arrests)

# Plot for Proportion of Arrests by Race per Precinct
arrest_proportions_plot_precinct <- ggplot(arrest_proportions_by_race, aes(x = Precinct, y = Proportion, fill = Subject_Race)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  theme_minimal() +
  labs(x = "Precinct", y = "Proportion of Arrests", title = "Proportion of Arrests by Race per Precinct") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))

# Plot for Proportion of Arrests by Race per Beat
arrest_proportions_plot_beat <- ggplot(arrest_proportions_by_race, aes(x = Beat, y = Proportion, fill = Subject_Race)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 1)) +
  labs(x = "Beat", y = "Proportion of Arrests", title = "Proportion of Arrests by Race per Beat") 

ggsave(here("images", paste(trial_name, "Precinct_Proportion_of_Arrests.png", sep = "_")),
       plot = arrest_proportions_plot_precinct, width = 13, height = 6.5, units = "in")

ggsave(here("images", paste(trial_name, "Beat_Proportion_of_Arrests.png", sep = "_")),
       plot = arrest_proportions_plot_beat , width = 13, height = 6.5, units = "in")

arrest_proportions_plot_precinct
arrest_proportions_plot_beat
```


```{r}
 SPD_Cluster_Data <- arrest_proportions_by_race %>%
  pivot_wider(names_from = Subject_Race, values_from = Proportion, values_fill = list(Proportion = 0))

head(SPD_Cluster_Data)
```


```{r}
# Perform k-means clustering 
SPD_Cluster_Data_Beat <- SPD_Cluster_Data %>%
  group_by(Beat) %>%
  summarize(
    across(all_of(race_columns), mean, .names = "{.col}_mean"),
    Total_Arrests = sum(Arrest_Count),
    .groups = 'drop'
  ) %>%
  mutate(Arrest_Count_Scaled = scale(Total_Arrests)) # Use the summarized Arrest_Count for scaling

set.seed(123)
k <- 6
# Ensure you use the new column names generated by `.names = "{.col}_mean"`
cluster_result <- kmeans(select(SPD_Cluster_Data_Beat, ends_with("_mean"), Arrest_Count_Scaled), centers = k)

# Optionally, add the cluster assignments back to the data for further analysis or visualization
SPD_Cluster_Data_Beat$Cluster <- cluster_result$cluster


cluster_plot <- ggplot(SPD_Cluster_Data_Beat, aes(x = Beat, y = Total_Arrests, color = factor(Cluster))) +
  geom_point(size = 4, alpha = 0.6) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 1)) +
  labs(color = "Cluster", title = "Cluster Assignment by Beat and Arrest Count")

ggsave(here("images", paste(trial_name, "cluster_Data_by_Beat.png", sep = "_")),
       plot = cluster_plot, width = 10, height = 4.5, units = "in")

cluster_plot 
```


```{r}
SPD_Cluster_Data_Precinct <- SPD_Cluster_Data %>%
  mutate(Arrest_Count_Scaled = scale(Arrest_Count))

set.seed(123)
k <- 6

cluster_result_precinct <- kmeans(select(SPD_Cluster_Data_Precinct, all_of(race_columns), Arrest_Count_Scaled), centers = k)

SPD_Cluster_Data_Precinct$Cluster <- cluster_result_precinct$cluster

cluster_plot_precinct <- ggplot(SPD_Cluster_Data_Precinct, aes(x = Precinct, y = Arrest_Count_Scaled, color = factor(Cluster))) +
  geom_point(size = 4, alpha = 0.6) +
  theme_minimal() +
  labs(color = "Cluster", title = "Cluster Assignment by Precinct")

ggsave(here("images", paste(trial_name, "cluster_Data_by_Precinct.png", sep = "_")), plot = cluster_plot_precinct, width = 10, height = 4.5, units = "in")

cluster_plot_precinct

```


```{r}
set_urbn_defaults(style = "map")

# read in reporting district shapefile 
rd <- st_read("~/Documents/Development/DAT4500/Data/SPD Reporting Beats.geojson",
             stringsAsFactors = FALSE, quiet = TRUE) %>%
             rename(Beat = beat)

rdPrecient <- rd %>%
  left_join(SPD_Cluster_Data_Precinct, by = "Beat")

cluster_map_plot_Precient <- ggplot() +
  geom_sf(data = rdPrecient, mapping = aes(fill = as.factor(Cluster))) +
  labs(title = "Arrest Analysis by Precinct", fill = "Cluster") 

ggsave(here("images", paste(trial_name, "cluster_map_by_Precient.png", sep = "_")),
       plot = cluster_map_plot_Precient, width = 10, height = 4.5, units = "in")

cluster_map_plot_Precient 
```


```{r}
set_urbn_defaults(style = "map")

rdBeat <- rd %>%
  left_join(SPD_Cluster_Data_Beat, by = "Beat")

cluster_map_plot <- ggplot() +
  geom_sf(data = rdBeat, mapping = aes(fill = as.factor(Cluster))) +
  labs(title = "Arrest Analysis by Precinct", fill = "Cluster") 

ggsave(here("images", paste(trial_name, "cluster_map_by_Beat.png", sep = "_")),
       plot = cluster_map_plot, width = 10, height = 4.5, units = "in")

cluster_map_plot  
```


```{r}
rd2 <- st_read("~/Documents/Development/DAT4500/Data/Race_and_Social_Equity_Composite_Index_Current_5634088353558588547.geojson",
             stringsAsFactors = FALSE, quiet = TRUE) 

demographic_map <- ggplot(data = rd2) +
  geom_sf(aes(fill = RACE_ELL_ORIGINS_QUINTILE)) + # Choose the demographic variable you want to plot
  labs(title = 'Percent People of Color by Area', fill = '% People of Color') 

demographic_map
```


```{r}
## calculating proportions need to add in sensus data after the slash so the division is correct 

arr_rate_a <- (arrest_counts_by_race$Subject_Race == "Asian") / sum(data$a_pop_count.2018)
arr_rate_b <- sum(arrest_counts_by_race$Subject_Race == "Black or African American") / sum(data$b_pop_count.2018)
arr_rate_w <- sum(arrest_counts_by_race$Subject_Race == "White") / sum(data$w_pop_count.2018)
arr_rate_u <- sum(arrest_counts_by_race$Subject_Race == "Unknown") / sum(data$h_pop_count.2018)
arr_rate_hw <- sum(arrest_counts_by_race$Subject_Race == "Native Hawaiian or Other Pacific Islander") / sum(data$h_pop_count.2018)
arr_rate_an <- sum(arrest_counts_by_race$Subject_Race == "American Indian or Alaska Native") / sum(data$h_pop_count.2018)

```

